Antd redesign
argoproj/argo-ui pull request #161
Opened 2021-10-21 13:18 UTC by plakyda-codefresh

2021-11-30 23:47 UTC, rbreeze requested changes
LGTM, but can we replace the button and input in the `v2/components` directory with these before merging?

2021-12-01 17:07 UTC, rbreeze approved these changes
After discussion, we've decided to merge this PR _without_ replacing `v2/components`, but plan on making the replacement once the Ant components have been tested, targeting for 2 weeks from now.

Thanks @plakyda-codefresh !

2021-12-01 17:08 UTC, plakyda-codefresh commented
@rbreeze Thanks 🙏

2021-12-01 22:19 UTC, alexmt approved these changes

2021-12-01 22:19 UTC, merged